import { Arsenal_SC, Raleway } from "next/font/google";
import "./globals.css";

const arsenal_sc = Arsenal_SC({
  variable: "--font-arsenal-sc",
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${arsenal_sc.variable} ${raleway.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
